services:
  db:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - .:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - wallet

  app:
    build: .
    tty: true
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wallet

networks:
  wallet:
    driver: bridge